# goreleaser documentation https://goreleaser.com/customization/
version: 2

before:
  hooks:
    - go mod tidy

builds:
  -
    main: ./cmd/project-rising-heat
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      # note, there are places that assume linux, such as prh/config.go
    goarch:
      - arm # for raspberryPi
      - amd64 # for local

archives:
  - format: tar.gz

changelog:
  sort: asc
