-- +goose Up
alter table prh.daily_data
    add column summary_date    timestamp,
    add column bed_time_temp   float(8),
    add column fan_on          text,
    add column temperature_max float(8),
    add column temperature_avg float(8),
    add column temperature_sum float(8),
    add column feels_like_max  float(8),
    add column feels_like_avg  float(8),
    add column feels_like_sum  float(8),
    add column uv_max          float(8),
    add column uv_avg          float(8),
    add column uv_sum          float(8),
    add column rain_max        float(8),
    add column rain_avg        float(8),
    add column rain_sum        float(8),
    add column cloud_max       float(8),
    add column cloud_avg       float(8),
    add column cloud_sum       float(8);

-- +goose Down
alter table prh.daily_data
    drop column summary_date,
    drop column bed_time_temp,
    drop column fan_on,
    drop column temperature_max,
    drop column temperature_avg,
    drop column temperature_sum,
    drop column feels_like_max,
    drop column feels_like_avg,
    drop column feels_like_sum,
    drop column uv_max,
    drop column uv_avg,
    drop column uv_sum,
    drop column rain_max,
    drop column rain_avg,
    drop column rain_sum,
    drop column cloud_max,
    drop column cloud_avg,
    drop column cloud_sum;
